---
- hosts: localhost
  tasks:
    - name: Instancia ec2
      amazon.aws.ec2_instance:
        name: Clase-Grupo2
        key_name: grupo2_keypair
        availability_zone: us-east-1a
        instance_type: t2.micro
        network:
          assign_public_ip: true
        image_id: ami-053b0d53c279acc90
